[package]
name = "taper-hashmap"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
hashbrown = "0.15"
rand = "0.9"
xxhash-rust = { version = "0.8", features = ["xxh3"] }
arrow = { version = "54", default-features = false, features = ["ffi"] }

[[bench]]
name = "hashmap_bench"
harness = false
